version: '3.8'

services:
  # Backend API - Production
  webimar-api:
    build: ./webimar-api
    ports:
      - "8001:8001"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://webimar:webimar123@postgres:5432/webimar_api
      - ALLOWED_HOSTS=localhost,127.0.0.1,webimar-api
    depends_on:
      - postgres
    restart: unless-stopped

  # Frontend - Production
  webimar-react:
    build: ./webimar-react
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8001/api
      - NODE_ENV=production
    restart: unless-stopped

  # PostgreSQL - Production
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: webimar_api
      POSTGRES_USER: webimar
      POSTGRES_PASSWORD: webimar123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis - Production Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning

volumes:
  postgres_data: