name: Otomatik Deploy

on:
  push:
    branches:
      - '**'  # Tüm branch'lerdeki push'larda çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu klonla
        uses: actions/checkout@v4

      - name: Sunucuya deploy et
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd /home/akn/webimar
            git reset --hard
            git clean -fd
            git pull origin main

            # Systemd servis birimleri oluştur (varsa üzerine yazar)
            sudo tee /etc/systemd/system/webimar-api.service > /dev/null << 'EOF'
            [Unit]
            Description=Webimar Django API
            After=network.target

            [Service]
            User=akn
            Group=www-data
            WorkingDirectory=/home/akn/webimar/webimar-api
            Environment=PATH=/home/akn/webimar/webimar-api/venv/bin
            ExecStart=/home/akn/webimar/webimar-api/venv/bin/gunicorn --workers 3 --bind 0.0.0.0:8000 webimar_api.wsgi:application
            Restart=on-failure

            [Install]
            WantedBy=multi-user.target
            EOF

            sudo tee /etc/systemd/system/webimar-react.service > /dev/null << 'EOF'
            [Unit]
            Description=Webimar React Frontend
            After=network.target

            [Service]
            User=akn
            Group=www-data
            WorkingDirectory=/home/akn/webimar/webimar-react
            ExecStart=/usr/bin/npm exec serve -- -s build -l 3000
            Restart=on-failure

            [Install]
            WantedBy=multi-user-target
            EOF

            sudo systemctl daemon-reload
            sudo systemctl enable webimar-api webimar-react

            # Django API Deploy
            cd webimar-api
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            . venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
            python3 manage.py migrate
            python3 manage.py collectstatic --noinput

            # Systemd üzerinden Django servisini yeniden başlat
            sudo systemctl restart webimar-api

            # React Frontend Deploy
            cd ../webimar-react
            npm install
            echo "REACT_APP_API_BASE_URL=http://104.247.166.125:8000/api" > .env.production
            echo "REACT_APP_BACKEND_URL=http://104.247.166.125:8000" >> .env.production
            echo "NODE_ENV=production" >> .env.production
            echo "GENERATE_SOURCEMAP=false" >> .env.production
            echo "BUILD_TIME=$(date +%s)" >> .env.production
            rm -rf build
            npm run build

            # Systemd üzerinden React servisini yeniden başlat
            sudo systemctl restart webimar-react

            echo "Deploy işlemi tamamlandı."
